name: Agent — RGP–NS Smoke Test

on:
  workflow_dispatch:

jobs:
  rgp_ns_smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pyyaml matplotlib

      - name: Run synthetic smoke test
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          echo "→ Running RGP–NS agent (synthetic smoke)…"
          python agents/rgp_ns/self_test.py

      - name: Rebuild maps & commit results
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python generate_graph_data.py \
            --pulse-glob "pulse/**/*.yml" \
            --alias-map meta/aliases.yml \
            --tag-descriptions meta/tag_descriptions.yml \
            --out-js docs/data.js

          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: RGP–NS smoke results + pulse" || echo "nothing to commit"
          git push || true
