name: Suggest Mesh Academy Post

on:
  push:
    branches: [ main ]
    paths:
      - 'mesh_academy/**'
      - 'phi-mesh/mesh_academy/**'   # legacy path, kept for compatibility
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: auto-post-suggestion
  cancel-in-progress: false

jobs:
  suggest_post:
    runs-on: ubuntu-latest
    if: >
      hashFiles('mesh_academy/tools/drift_parser.py') != '' ||
      hashFiles('phi-mesh/mesh_academy/tools/drift_parser.py') != ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Determine paths (current vs legacy)
        id: paths
        shell: bash
        run: |
          if [[ -f mesh_academy/tools/drift_parser.py ]]; then
            echo "BASE=mesh_academy" >> $GITHUB_OUTPUT
          elif [[ -f phi-mesh/mesh_academy/tools/drift_parser.py ]]; then
            echo "BASE=phi-mesh/mesh_academy" >> $GITHUB_OUTPUT
          else
            echo "No drift_parser.py found."; exit 1
          fi
          echo "OUT_FILE=${{ steps.paths.outputs.BASE }}/logs/next_post_suggestion.md" >> $GITHUB_OUTPUT

      - name: Ensure logs folder exists
        run: |
          mkdir -p "${{ steps.paths.outputs.BASE }}/logs"

      - name: Run drift_parser.py (tag = alignment)
        run: |
          python "${{ steps.paths.outputs.BASE }}/tools/drift_parser.py" alignment > /tmp/suggestion.txt

      - name: Save suggestion as Markdown
        run: |
          {
            echo "### Suggested Course Based on Drift Tag: alignment"
            echo
            cat /tmp/suggestion.txt
          } > "${{ steps.paths.outputs.OUT_FILE }}"

      - name: Commit and push suggestion (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ steps.paths.outputs.OUT_FILE }}" || true
          git commit -m "chore(mesh_academy): add/update post suggestion from drift tag 'alignment'" || echo "No changes to commit"
          git push || true
