
import streamlit as st, pandas as pd, numpy as np, matplotlib.pyplot as plt

st.title("NT Metrics Dashboard")
st.write("Upload nt_times.txt generated by nt_detect.py")
file = st.file_uploader("nt_times.txt", type=["txt"])
if file is not None:
    nts = np.loadtxt(file)
    intervals = np.diff(nts)
    st.metric("Total NTs", len(nts))
    st.metric("Mean interval", intervals.mean() if len(intervals)>0 else 0.0)
    fig, ax = plt.subplots()
    ax.hist(intervals, bins=20, edgecolor='k')
    ax.set_xlabel("Inter-NT interval")
    st.pyplot(fig)
