# Minimal config; synthetic by default. Swap to local_netcdf later.

dataset:
  kind: synthetic
  slug: demo_rgpsynth
  duration: 10.0
  dt: 0.01
  n_probes: 3
  seed: 0

# NT detector params
proxy_window: 5     # moving-mean window for roughness proxy
min_sep: 5          # min samples between peaks
rel_prom: 0.2       # peak threshold as fraction of max(proxy)

# Pulse metadata
title: 'NT Rhythm — RGP-NS dry run'
tags: [nt_rhythm, rgp, navier_stokes]
