name: Agent — RGP-NS Smoke

on:
  push:
    paths:
      - 'agents/rgp_ns/**'
      - '.github/workflows/agent_rgpsmoke.yml'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml numpy

      - name: Run synthetic smoke test
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python agents/rgp_ns/self_test.py

            - name: Rebuild maps
        run: |
          python generate_graph_data.py \
            --pulse-glob "pulse/**/*.yml" \
            --alias-map meta/aliases.yml \
            --tag-descriptions meta/tag_descriptions.yml \
            --out-js docs/data.js

      - name: Commit & push results
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: RGP–NS smoke results + pulse" || echo "nothing to commit"
          git push || true
