name: Agent — FD Jobs → Pulse

on:
  push:
    paths:
      - 'inbox/fd_jobs/*.yml'
  workflow_dispatch: {}

jobs:
  agent_fd_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml numpy

      - name: Process FD jobs
        run: |
          mkdir -p results/fd_probe
          mkdir -p pulse/auto

          for jobfile in inbox/fd_jobs/*.yml; do
            [ -f "$jobfile" ] || continue

            echo "→ Running job $jobfile"

            # Slugify dataset name
            slug=$(grep '^dataset:' "$jobfile" | awk '{print $2}' | tr -dc '[:alnum:]_-' | tr '[:upper:]' '[:lower:]')
            source=$(grep '^source:' "$jobfile" | awk '{print $2}' | tr -dc '[:alnum:]_-' | tr '[:upper:]' '[:lower:]')
            base="${slug}-${source}"

            # Count existing results for today to allocate batchN
            today=$(date +%Y-%m-%d)
            count=$(ls results/fd_probe/${base}_batch*.metrics.json 2>/dev/null | grep "$today" | wc -l)
            batch=$((count + 1))

            metrics="results/fd_probe/${base}_batch${batch}.metrics.json"
            echo "  Allocated: $metrics"

            # Run agent
            python tools/agent_rhythm/agent_fd_job_runner.py --job "$jobfile" --json-out "$metrics"

            # Convert metrics to pulse
            title=$(grep '^title:' "$jobfile" | cut -d: -f2- | xargs)
            tags=$(grep '^tags:' -A 10 "$jobfile" | grep '-' | sed 's/-//g' | xargs)

            python tools/agent_rhythm/make_pulse.py \
              --metrics "$metrics" \
              --title "$title" \
              --dataset "${base}_batch${batch}" \
              --tags "$tags" \
              --outdir pulse/auto

            # Archive jobfile
            mv "$jobfile" inbox/fd_jobs/_done/ || true
          done

      - name: Commit results + pulses
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "bot@phi-mesh.local"
          git add results/ pulse/auto/ inbox/fd_jobs/_done/
          git commit -m "auto: Agent FD jobs → pulses + updated maps" || echo "No changes"
          git push
