name: Agent — RGP-NS Smoke

on:
  push:
    paths:
      - 'agents/rgp_ns/**'
      - '.github/workflows/agent_rgpsmoke.yml'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          # Keep it light; no SciPy needed for the smoke wrapper.
          python -m pip install pyyaml

      - name: Run synthetic smoke test
        run: |
          python agents/rgp_ns/self_test.py
