name: Agent — FD Jobs → Pulse

on:
  workflow_dispatch: {}   # allow manual trigger from GitHub UI
  push:
    paths:
      - 'inbox/fd_jobs/*.yml'          # auto-trigger on new/updated job files
      - '!inbox/fd_jobs/_templates/**' # ignore template files

jobs:
  fd_job_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run FD Agent Job
        run: |
          python tools/agent_rhythm/agent_fd_job_runner.py \
            --inbox inbox/fd_jobs \
            --out-pulse pulse/auto \
            --out-results results/fd_probe

      - name: Commit & push results
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "actions@github.com"
          git add pulse/auto results/fd_probe
          git commit -m "auto: Agent FD jobs → pulses + updated maps" || echo "No changes"
          git push
