name: Archive Orphan JHTDB Evidence

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sweep orphan evidence into archive/
        shell: bash
        run: |
          set -euo pipefail
          python tools/fd_connectors/jhtdb/archive_orphan_jhtdb.py

      - name: Commit archive moves
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Capture moves/renames/deletions within data/jhtdb
          git add -A data/jhtdb
          if git diff --cached --quiet; then
            echo "Nothing to archive."
            exit 0
          fi
          git commit -m "chore(jhtdb): archive orphan evidence files"
          git pull --rebase origin main || true
          git push
