name: Archive Orphan JHTDB Evidence

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sweep orphan evidence into archive/
        run: |
          set -euo pipefail
          python tools/fd_connectors/jhtdb/archive_orphan_jhtdb.py

      - name: Commit archive moves
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/jhtdb/archive/* 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "Nothing to archive."
            exit 0
          fi
          git commit -m "chore(jhtdb): archive orphan evidence files"
          git pull --rebase origin main || true
          git push
