name: Clean Pulses (minimal schema)

on:
  workflow_dispatch:
  push:
    paths:
      - 'pulse/**/*.yml'
      - 'pulse/**/*.yaml'
      - 'tools/clean_pulses_minimal.py'

concurrency:
  group: clean-pulses
  cancel-in-progress: false

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Dry-run (detect changes loudly)
        run: |
          python tools/clean_pulses_minimal.py --check || echo "Changes needed"

      - name: Apply fixes
        run: |
          python tools/clean_pulses_minimal.py --write

      - name: Show what changed
        run: |
          echo "---- git status ----"
          git status --porcelain
          echo "---- changed files ----"
          git diff --name-only | sed -n '1,200p' || true
          echo "---- sample diff (first 2 files) ----"
          for f in $(git diff --name-only | head -n 2); do
            echo "==== $f ===="
            git diff -- $f | sed -n '1,200p'
          done

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pulse/**/*.yml pulse/**/*.yaml || true
          git commit -m "chore: clean pulses to minimal schema (title,date,summary,tags,papers,podcasts)" || echo "No changes to commit"
          git push || true
