name: Clean Pulses (minimal schema)

on:
  workflow_dispatch:
  push:
    paths:
      - 'pulse/**/*.yml'
      - 'pulse/**/*.yaml'
      - 'tools/clean_pulses_minimal.py'

permissions:
  contents: write

concurrency:
  group: clean-pulses
  cancel-in-progress: true

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Dry-run (detect changes)
        run: |
          python tools/clean_pulses_minimal.py --check || echo "Changes needed"

      - name: Apply fixes
        run: |
          python tools/clean_pulses_minimal.py --write

      - name: Commit cleaned pulses (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage all changes beneath pulse/
          git add -A pulse/

          # No changes? exit quietly
          git diff --cached --quiet && echo "No changes to commit" && exit 0

          echo "Changes detected:"
          git status --porcelain | sed -n '1,200p' || true

          git commit -m "chore: clean pulses to minimal schema (title,date,summary,tags,papers,podcasts)"
          git pull --rebase origin main || true
          git push
