name: NT Rhythm — FD Probe to Pulse

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Data source (synthetic | jhtdb | nasa)'
        required: true
        default: 'synthetic'
      dataset:
        description: 'Dataset name or slug (free text; will be auto-sanitized)'
        required: true
        default: 'demo'
      var:
        description: 'Variable name'
        required: true
        default: 'u'
      xyz:
        description: 'Probe point as x,y,z'
        required: true
        default: '0.1,0.1,0.1'
      twin:
        description: 'Time window as t0,t1,dt'
        required: true
        default: '0.0,10.0,0.01'
      title:
        description: 'Pulse title'
        required: true
        default: 'NT Rhythm — FD Probe'
      tags:
        description: 'Space-separated tags'
        required: true
        default: 'nt_rhythm turbulence navier_stokes rgp'

permissions:
  contents: write

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip pyyaml numpy

      # Sanitize dataset slug (for filenames) and compute result_base used by the runner's latest pointer
      - name: Resolve & validate inputs
        id: inp
        shell: python
        run: |
          import os, re
          def safe_slug(s:str)->str:
              s = (s or "").strip().lower()
              s = re.sub(r"[^a-z0-9._-]+","_", s)
              s = re.sub(r"_+","_", s).strip("_")
              return s or "dataset"
          ds_in = os.environ["DATASET_IN"]
          slug = safe_slug(ds_in)
          src  = os.environ["SRC_IN"].strip().lower()
          # echo outputs
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"slug={slug}\n")
              f.write(f"source={src}\n")
          print(f"::notice::Using dataset slug = {slug} (source={src})")
        env:
          DATASET_IN: ${{ github.event.inputs.dataset }}
          SRC_IN:     ${{ github.event.inputs.source }}

      - name: Run FD probe (auto-batch + latest pointer)
        env:
          PYTHONPATH: ${{ github.workspace }}
          JHTDB_OFFLINE: ${{ secrets.JHTDB_OFFLINE }}
          JHTDB_TOKEN:   ${{ secrets.JHTDB_TOKEN }}
          NASA_CSV:      ${{ secrets.NASA_CSV }}
        run: |
          python tools/fd_connectors/run_fd_probe.py \
            --source "${{ steps.inp.outputs.source }}" \
            --dataset "${{ steps.inp.outputs.slug }}" \
            --var "${{ github.event.inputs.var }}" \
            --xyz "${{ github.event.inputs.xyz }}" \
            --twin "${{ github.event.inputs.twin }}"

      - name: Emit pulse YAML
        run: |
          # The runner wrote a stable pointer:
          #   results/fd_probe/<slug>-<source>_latest.metrics.json
          METRICS="results/fd_probe/${{ steps.inp.outputs.slug }}-${{ steps.inp.outputs.source }}_latest.metrics.json"
          if [ ! -f "$METRICS" ]; then
            echo "Latest metrics not found: $METRICS"
            ls -la results/fd_probe || true
            exit 1
          fi
          python tools/agent_rhythm/make_pulse.py \
            --metrics "$METRICS" \
            --title   "${{ github.event.inputs.title }}" \
            --dataset "${{ steps.inp.outputs.slug }}" \
            --tags    "${{ github.event.inputs.tags }}" \
            --outdir  pulse/auto

      - name: Rebuild maps
        run: |
          python generate_graph_data.py \
            --pulse-glob "pulse/**/*.yml" \
            --alias-map meta/aliases.yml \
            --tag-descriptions meta/tag_descriptions.yml \
            --out-js docs/data.js

      - name: Commit & push
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: FD probe (${{ steps.inp.outputs.slug }}-${{ steps.inp.outputs.source }}) pulse + updated maps" || echo "nothing to commit"
          git push || true
