name: NT Rhythm — FD Probe to Pulse

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Data source'
        required: true
        default: 'jhtdb'   # or 'nasa'
      dataset:
        description: 'Dataset slug'
        required: true
      var:
        description: 'Variable name'
        required: true
        default: 'u'
      point:
        description: 'Point as x,y,z'
        required: true
        default: '0.1,0.1,0.1'
      window:
        description: 't0,t1,dt'
        required: true
        default: '0.0,10.0,0.01'
      title:
        description: 'Pulse title'
        required: true
        default: 'NT Rhythm — FD Probe'
      tags:
        description: 'Space-separated tags'
        required: true
        default: 'nt_rhythm turbulence navier_stokes rgp'

permissions:
  contents: write

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip pyyaml numpy
      - name: Run FD probe
        env:
          JHTDB_OFFLINE: ${{ secrets.JHTDB_OFFLINE }}
        run: |
          python tools/fd_connectors/run_fd_probe.py \
            --source "${{ github.event.inputs.source }}" \
            --dataset "${{ github.event.inputs.dataset }}" \
            --var "${{ github.event.inputs.var }}" \
            --point "${{ github.event.inputs.point }}" \
            --window "${{ github.event.inputs.window }}" \
            --title "${{ github.event.inputs.title }}" \
            --tags "${{ github.event.inputs.tags }}"
      - name: Rebuild maps
        run: |
          python generate_graph_data.py \
            --pulse-glob "pulse/**/*.yml" \
            --alias-map meta/aliases.yml \
            --tag-descriptions meta/tag_descriptions.yml \
            --out-js docs/data.js
      - name: Commit & push
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: FD probe pulse + updated maps" || echo "nothing to commit"
          git push || true
