name: NT Rhythm — FD Probe to Pulse

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Data source (synthetic | jhtdb | nasa)'
        required: true
        default: 'synthetic'
      dataset:
        description: 'Dataset name or slug (free text; will be auto-sanitized)'
        required: true
        default: 'demo'
      var:
        description: 'Variable name'
        required: true
        default: 'u'
      xyz:
        description: 'Probe point as x,y,z'
        required: true
        default: '0.1,0.1,0.1'
      twin:
        description: 'Time window as t0,t1,dt'
        required: true
        default: '0.0,10.0,0.01'
      title:
        description: 'Pulse title'
        required: true
        default: 'NT Rhythm — FD Probe'
      tags:
        description: 'Space-separated tags'
        required: true
        default: 'nt_rhythm turbulence navier_stokes rgp'

permissions:
  contents: write

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip pyyaml numpy

      # Sanitize dataset slug, validate xyz/twin shape, and append a run suffix to avoid overwrites.
      - name: Resolve & validate inputs
        id: inp
        shell: python
        env:
          DATASET_IN: ${{ github.event.inputs.dataset }}
          XYZ_IN:     ${{ github.event.inputs.xyz }}
          TWIN_IN:    ${{ github.event.inputs.twin }}
          RUN_NO:     ${{ github.run_number }}
        run: |
          import os, re, sys
          def safe_slug(s:str)->str:
              s = (s or "").strip().lower()
              s = re.sub(r"[^a-z0-9._-]+","_", s)
              s = re.sub(r"_+","_", s).strip("_")
              return s or "dataset"
          def parse_triplet(label, s):
              parts = [p.strip() for p in (s or "").split(",")]
              if len(parts) != 3:
                  print(f"::error::{label} must be 'a,b,c' (got: {s!r})")
                  sys.exit(1)
              return parts
          ds_in   = os.environ["DATASET_IN"]
          xyz_in  = os.environ["XYZ_IN"]
          twin_in = os.environ["TWIN_IN"]
          run_no  = os.environ.get("RUN_NO","")
          slug = safe_slug(ds_in)
          # validate shapes
          _ = parse_triplet("xyz", xyz_in)
          _ = parse_triplet("twin", twin_in)
          # auto-unique suffix to avoid filename collisions per day
          uniq = f"{slug}-{run_no}" if run_no else slug
          print(f"::notice::Using dataset slug = {uniq}")
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"slug={uniq}\n")

      - name: Run FD probe
        env:
          PYTHONPATH: ${{ github.workspace }}
          JHTDB_OFFLINE: ${{ secrets.JHTDB_OFFLINE }}
          JHTDB_TOKEN: ${{ secrets.JHTDB_TOKEN }}
          NASA_CSV: ${{ secrets.NASA_CSV }}
        run: |
          mkdir -p results/fd_probe
          python tools/fd_connectors/run_fd_probe.py \
            --source "${{ github.event.inputs.source }}" \
            --dataset "${{ steps.inp.outputs.slug }}" \
            --var "${{ github.event.inputs.var }}" \
            --xyz "${{ github.event.inputs.xyz }}" \
            --twin "${{ github.event.inputs.twin }}" \
            --json-out "results/fd_probe/${{ steps.inp.outputs.slug }}.metrics.json"

      - name: Emit pulse YAML
        run: |
          python tools/agent_rhythm/make_pulse.py \
            --metrics "results/fd_probe/${{ steps.inp.outputs.slug }}.metrics.json" \
            --title   "${{ github.event.inputs.title }}" \
            --dataset "${{ steps.inp.outputs.slug }}" \
            --tags    "${{ github.event.inputs.tags }}" \
            --outdir  pulse/auto

      - name: Rebuild maps
        run: |
          python generate_graph_data.py \
            --pulse-glob "pulse/**/*.yml" \
            --alias-map meta/aliases.yml \
            --tag-descriptions meta/tag_descriptions.yml \
            --out-js docs/data.js

      - name: Commit & push
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: FD probe (${{ steps.inp.outputs.slug }}) pulse + updated maps" || echo "nothing to commit"
          git push || true
