name: FD probe (isotropic1024coarse → metrics + pulse)

on:
  workflow_dispatch:
    inputs:
      source:
        description: "synthetic | jhtdb | nasa"
        required: true
        default: "jhtdb"
      dataset:
        description: "dataset name/slug or path (free text; will be auto-sanitized)"
        required: true
        default: "isotropic1024coarse"
      var:
        description: "variable name"
        required: true
        default: "u"
      xyz:
        description: "probe point as x,y,z"
        required: true
        default: "0.1,0.1,0.1"
      twin:
        description: "time window as t0,t1,dt"
        required: true
        default: "0.0,0.4,0.0001"
      title:
        description: "pulse title"
        required: true
        default: "NT Rhythm — FD Probe"
      tags:
        description: "space-separated tags"
        required: true
        default: "nt_rhythm turbulence navier_stokes rgp"

permissions:
  contents: write

jobs:
  fd-probe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml numpy

      # -------- prepare today's folder + batch number (resets daily) ----------
      - name: Normalize inputs and compute today's batch label
        id: prep
        shell: bash
        env:
          SRC: ${{ github.event.inputs.source }}
          DATASET: ${{ github.event.inputs.dataset }}
        run: |
          set -euo pipefail

          TODAY=$(date +%F)                        # e.g., 2025-09-06
          # sanitize dataset to slug
          py='import re,sys; s=sys.argv[1].strip().lower(); s=re.sub(r"[^a-z0-9._-]+","_",s); s=re.sub(r"_+","_",s).strip("_"); print(s or "dataset")'
          DS_SLUG=$(python -c "$py" "$DATASET")
          SRC_SLUG=$(echo "${SRC}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/_/g')
          BASE="${DS_SLUG}_${SRC_SLUG}"

          OUTDIR="results/fd_probe/${TODAY}"
          mkdir -p "${OUTDIR}"

          # Determine next batch number *within today's folder only*
          shopt -s nullglob
          NEXT=1
          existing=(${OUTDIR}/${BASE}_batch*.metrics.json)
          if [[ ${#existing[@]} -gt 0 ]]; then
            last=$(ls -1 ${OUTDIR}/${BASE}_batch*.metrics.json \
                   | sed -E 's/.*_batch([0-9]+)\.metrics\.json/\1/' \
                   | sort -n | tail -1)
            NEXT=$(( last + 1 ))
          fi
          METRICS="${OUTDIR}/${BASE}_batch${NEXT}.metrics.json"

          echo "today=${TODAY}"        >> "$GITHUB_OUTPUT"
          echo "base=${BASE}"          >> "$GITHUB_OUTPUT"
          echo "batch=${NEXT}"         >> "$GITHUB_OUTPUT"
          echo "metrics_path=${METRICS}" >> "$GITHUB_OUTPUT"

          echo "::notice title=Batch::Using ${TODAY}/${BASE}_batch${NEXT}"

      # -------------------------- run the probe -------------------------------
      - name: Run FD probe
        env:
          NASA_CSV: ${{ secrets.NASA_CSV }}
          JHTDB_TOKEN: ${{ secrets.JHTDB_TOKEN }}
        run: |
          set -euo pipefail
          python tools/fd_connectors/run_fd_probe.py \
            --source "${{ github.event.inputs.source }}" \
            --dataset "${{ github.event.inputs.dataset }}" \
            --var "${{ github.event.inputs.var }}" \
            --xyz "${{ github.event.inputs.xyz }}" \
            --twin "${{ github.event.inputs.twin }}" \
            --json-out "${{ steps.prep.outputs.metrics_path }}" \
            --title "${{ github.event.inputs.title }}" \
            --tags "${{ github.event.inputs.tags }}"

      # -------------------------- emit the pulse ------------------------------
      - name: Emit pulse (slug matches metrics basename with _batchN)
        run: |
          set -euo pipefail
          METRICS="${{ steps.prep.outputs.metrics_path }}"
          PULSE_SLUG=$(basename "$METRICS")         # <base>_batchN.metrics.json
          PULSE_SLUG="${PULSE_SLUG%.metrics.json}"  # <base>_batchN

          python tools/agent_rhythm/make_pulse.py \
            --metrics "$METRICS" \
            --title "${{ github.event.inputs.title }}" \
            --dataset "$PULSE_SLUG" \
            --tags "${{ github.event.inputs.tags }}" \
            --outdir "pulse/auto"

      # ------------------ commit results + pulse + maps -----------------------
      - name: Commit results + pulse + maps
        run: |
          set -euo pipefail
          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"

          git add "results/fd_probe/${{ steps.prep.outputs.today }}/*.json"
          git add pulse/auto/*.yml
          git add maps/* || true

          git commit -m "auto: FD probe (${{ steps.prep.outputs.base }}_batch${{ steps.prep.outputs.batch }}) pulse + updated maps" || echo "Nothing to commit"
          git push
