name: NT Rhythm — FD Probe to Pulse

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Data source (synthetic | jhtdb | nasa)'
        required: true
        default: 'synthetic'
      dataset:
        description: 'Dataset name/slug or path (free text; will be auto-sanitized)'
        required: true
        default: 'demo'
      var:
        description: 'Variable name'
        required: true
        default: 'u'
      xyz:
        description: 'Probe point as x,y,z'
        required: true
        default: '0.1,0.1,0.1'
      twin:
        description: 'Time window as t0,t1,dt'
        required: true
        default: '0.0,10.0,0.01'
      title:
        description: 'Pulse title'
        required: true
        default: 'NT Rhythm — FD Probe'
      tags:
        description: 'Space-separated tags'
        required: true
        default: 'nt_rhythm turbulence navier_stokes rgp'
      nasa_csv:
        description: 'NASA CSV path or URL (only used when source=nasa)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip pyyaml numpy

      - name: Resolve slug
        id: inp
        shell: python
        run: |
          import os, re
          def safe_slug(s:str)->str:
              s = (s or "").strip().lower()
              s = re.sub(r"[^a-z0-9._-]+","_", s)
              s = re.sub(r"_+","_", s).strip("_")
              return s or "dataset"
          ds = os.environ["DATASET_IN"]
          slug = safe_slug(ds)
          print(f"::notice::Using dataset slug = {slug}")
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"slug={slug}\n")
        env:
          DATASET_IN: ${{ github.event.inputs.dataset }}

      - name: Compute metrics (batch-numbered)
        id: compute
        env:
          PYTHONPATH: ${{ github.workspace }}
          JHTDB_OFFLINE: ${{ secrets.JHTDB_OFFLINE }}
          JHTDB_TOKEN:   ${{ secrets.JHTDB_TOKEN }}
          NASA_CSV:      ${{ github.event.inputs.nasa_csv || secrets.NASA_CSV }}
        run: |
          set -euo pipefail
          mkdir -p results/fd_probe
          slug="${{ steps.inp.outputs.slug }}"
          i=1
          while true; do
            cand="results/fd_probe/${slug}_batch${i}.metrics.json"
            if [ ! -f "$cand" ]; then
              JSON_OUT="$cand"
              break
            fi
            i=$((i+1))
          done
          echo "json_out=$JSON_OUT" >> "$GITHUB_OUTPUT"

          python tools/fd_connectors/run_fd_probe.py \
            --source "${{ github.event.inputs.source }}" \
            --dataset "$slug" \
            --var "${{ github.event.inputs.var }}" \
            --xyz "${{ github.event.inputs.xyz }}" \
            --twin "${{ github.event.inputs.twin }}" \
            --json-out "$JSON_OUT"

      - name: Emit pulse YAML (batch-numbered)
        run: |
          python tools/agent_rhythm/make_pulse.py \
            --metrics "${{ steps.compute.outputs.json_out }}" \
            --title   "${{ github.event.inputs.title }}" \
            --dataset "${{ steps.inp.outputs.slug }}" \
            --tags    "${{ github.event.inputs.tags }}" \
            --outdir  pulse/auto

      - name: Rebuild maps
        run: |
          python generate_graph_data.py \
            --pulse-glob "pulse/**/*.yml" \
            --alias-map meta/aliases.yml \
            --tag-descriptions meta/tag_descriptions.yml \
            --out-js docs/data.js

      - name: Commit & push
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: FD probe (${{ steps.inp.outputs.slug }}) batch update + maps" || echo "nothing to commit"
          git push || true
