name: Patch-Runner

on:
  push:
    paths:
      - 'incoming/*.patch'

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting patch apply job"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "PhiMeshBot"
          git config user.email "actions@github.com"

      - name: Apply patch and open PR
        run: |
          for patch in incoming/*.patch; do
            echo "Applying $patch"
            git apply --verbose "$patch"
            branch="patch-$(basename $patch .patch)"
            git checkout -b "$branch"
            git add .
            git commit -m "Apply patch $patch"
            git push origin "$branch"
            gh pr create --fill --base main --head "$branch"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
