name: Patch-Runner

on:
  push:
    paths:
      - 'incoming/*.patch'

jobs:
  apply-patch:
    name: Apply Patch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "patch-runner[bot]"
          git config user.email "patch-runner@users.noreply.github.com"

      - name: Apply patch and open PR
        run: |
          for patch in incoming/*.patch; do
            ts=$(date +%Y%m%d_%H%M)
            branch="auto/patch-${ts}"
            git apply "$patch"
            git checkout -b "$branch"
            git add -A
            git commit -m "Auto-PR: apply patch $patch"
            git push origin "$branch"
            gh pr create --title "Auto-PR: $patch" --body "Patch auto-applied via Patch-Runner." --base main --head "$branch"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
