name: Patch-Runner

on:
  push:
    paths:
      - 'incoming/*.patch'

jobs:
  apply-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Apply patch from incoming/
        run: |
          for patch in incoming/*.patch; do
            git apply "$patch"
            ts=$(date +%Y%m%d_%H%M)
            branch="auto/patch-${ts}"
            git checkout -b "$branch"
            git add -A
            git commit -m "Auto-PR: apply patch $patch"
            git push origin "$branch"
            gh pr create --title "Auto-PR: $patch" --body "Patch auto-applied via Patch-Runner." --base main --head "$branch"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
