name: Φ‑Pulse Logger

on:
  push:
    branches:
      - main
      - o3
  workflow_dispatch:

permissions:
  contents: write

jobs:
  log-pulse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Append pulse entry
        env:
          GIT_TRACE: 1
        run: |
          set -eux
          dt=$(date -u +'%F')
          mkdir -p pulse
          touch pulse/${dt}.yml
          python scripts/delta_phi.py || true
          echo "- sha: HEAD author: auto ΔΦ: $(cat delta_phi.txt || echo 'n/a')" >> ./pulse/${dt}.yml

      - name: Commit and push pulse entry   # <--- the new block
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add pulse/
          git commit -m "Add daily pulse entry for $(date -u +'%F')" || echo "No changes to commit"
          git push
