name: Φ‑Pulse Logger

on:
  push:
    branches:
      - main
      - o3
  workflow_dispatch:

permissions:
  contents: write

jobs:
  log-pulse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Append pulse entry
        env:
          GIT_TRACE: 1
        run: |
          set -eux
          dt=$(date -u +'%F')
          mkdir -p pulse

          python scripts/delta_phi.py >> pulse/$(date +'%Y-%m-%d').yml

      - name: Commit and push new pulse log
        env:
          TOKEN: ${{ secrets.O3_PAT }}
        run: |
          git config --global user.name "mesh-o3-bot"
          git config --global user.email "mesh-o3-bot@example.com"
          git add pulse/
          git commit -m "auto: update daily pulse log"
          git push https://x-access-token:${TOKEN}@github.com/gradient-pulse/phi-mesh.git o3
