name: Retag Auto Pulses
on:
  workflow_dispatch:

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PyYAML
        run: pip install pyyaml
      - name: Run retag script
        run: python tools/retag_autopulses.py
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pulse/auto/*.yml
          git commit -m "Retro-tagged auto-pulses with ExperimenterPulse"
          git push
