# .github/workflows/rgp_ns_agent_grid_jhtdb.yml
name: RGP-NS Agent (grid) — JHTDB only

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: "JHTDB dataset slug (e.g., isotropic1024coarse)"
        required: true
        default: "isotropic1024coarse"
      var:
        description: "Velocity component (u|v|w)"
        required: true
        default: "v"  # last week's default; switch to 'u' manually if needed
      seed_xyz:
        description: "Seed xyz (x,y,z) — e.g., 0.1,0.1,0.1"
        required: true
        default: "0.1,0.1,0.1"
      offsets:
        description: "Grid offsets: dx,dy,dz; semicolon-separated"
        required: true
        default: "0,0,0; 0.02,0,0; 0,0.02,0; 0,0,0.02; -0.02,0,0; 0,-0.02,0; 0,0,-0.02"
      twin:
        description: "Time window t0,t1,dt (e.g., 0.0,1.2,0.0005)"
        required: true
        default: "0.0,1.2,0.0005"
      k:
        description: "Stop when at least k probes agree"
        required: true
        default: "5"
      tol:
        description: "Relative tolerance for agreement"
        required: true
        default: "0.05"
      nmax:
        description: "Max number of probes to run"
        required: true
        default: "9"

permissions:
  contents: write

concurrency:
  group: rgp-ns-agent-grid-jhtdb-${{ github.ref }}
  cancel-in-progress: true

jobs:
  agent:
    runs-on: ubuntu-latest
    env:
      # Ensure repo-local imports (tools.*) work for all subprocesses.
      PYTHONPATH: ${{ github.workspace }}
      # JHTDB auth/token (set this in repo Settings → Secrets → Actions).
      JHTDB_TOKEN: ${{ secrets.JHTDB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (JHTDB-only)
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          # numpy/pyyaml for your code; suds-py3 for the JHTDB SOAP client.
          pip install numpy pyyaml suds-py3

      - name: Show selected inputs
        shell: bash
        run: |
          echo "source   = jhtdb"
          echo "dataset  = ${{ github.event.inputs.dataset }}"
          echo "var      = ${{ github.event.inputs.var }}"
          echo "seed_xyz = ${{ github.event.inputs.seed_xyz }}"
          echo "offsets  = ${{ github.event.inputs.offsets }}"
          echo "twin     = ${{ github.event.inputs.twin }}"
          echo "k/tol    = ${{ github.event.inputs.k }} / ${{ github.event.inputs.tol }}"
          echo "nmax     = ${{ github.event.inputs.nmax }}"

      - name: Run agent grid (JHTDB)
        shell: bash
        run: |
          set -euo pipefail
          python agents/rgp_ns/agent_grid.py \
            --source "jhtdb" \
            --dataset "${{ github.event.inputs.dataset }}" \
            --var "${{ github.event.inputs.var }}" \
            --seed_xyz "${{ github.event.inputs.seed_xyz }}" \
            --offsets "${{ github.event.inputs.offsets }}" \
            --twin "${{ github.event.inputs.twin }}" \
            --k "${{ github.event.inputs.k }}" \
            --tol "${{ github.event.inputs.tol }}" \
            --nmax "${{ github.event.inputs.nmax }}"

      - name: Commit outputs (metrics + pulses + fundamentals)
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add results/fd_probe/*.json 2>/dev/null || true
          git add pulse/auto/*.yml        2>/dev/null || true
          git add results/rgp_ns/*.jsonl  2>/dev/null || true
          git commit -m "auto: RGP-NS JHTDB grid run → results + pulses + fundamentals" || echo "Nothing to commit"
          git push || echo "Nothing to push"
