name: RGP-NS Agent Runner

on:
  workflow_dispatch:
    inputs:
      autopulse:
        description: "Write auto pulses (yes/no)"
        required: true
        default: "no"

permissions:
  contents: write

concurrency:
  group: rgp-ns-runner
  cancel-in-progress: false

jobs:
  run:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.autopulse == 'yes' }}
    runs-on: ubuntu-latest
    env:
      ENABLE_AUTOPULSE: "1"  # gate inside run_agent.py

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ -f requirements.txt ]]; then
            pip install -r requirements.txt
          else
            pip install pyyaml jq
          fi

      - name: Run agent (writes pulses itself)
        run: python agents/rgp_ns/run_agent.py

      - name: Rebuild Tag Map data
        run: |
          mkdir -p docs
          python generate_graph_data.py \
            --pulse-glob "pulse/**/*.yml" \
            --alias-map meta/aliases.yml \
            --tag-descriptions meta/tag_descriptions.yml \
            --out-js docs/data.js

      - name: Commit results, pulses, and map
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: RGP-NS run (results, pulses, docs/data.js)" || echo "nothing to commit"
          git push || true
