name: RGP-NS Agent Runner

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * 2"  # Tuesdays 03:17 UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check secrets (warn only)
        run: |
          warn=""
          check() {
            name="$1"
            case "$name" in
              JHTDB_TOKEN) val="${{ secrets.JHTDB_TOKEN }}" ;;
              ZENODO_DOI) val="${{ secrets.ZENODO_DOI }}" ;;
              X_WEBHOOK_URL) val="${{ secrets.X_WEBHOOK_URL }}" ;;
            esac
            if [ -z "$val" ]; then
              echo "⚠️  Warning: $name not set"
              warn=1
            else
              echo "✅ $name present"
            fi
          }
          check JHTDB_TOKEN
          check ZENODO_DOI
          check X_WEBHOOK_URL
          if [ -n "$warn" ]; then
            echo "Continuing (warnings only)."
          fi

      - name: Execute agent loop
        env:
          JHTDB_TOKEN: ${{ secrets.JHTDB_TOKEN }}
          ZENODO_DOI:  ${{ secrets.ZENODO_DOI }}
          X_WEBHOOK_URL: ${{ secrets.X_WEBHOOK_URL }}
        run: python agents/rgp_ns/run_agent.py

      - name: Debug — show new files
        run: |
          echo "Tree after agent run:"
          ls -la
          echo "--- pulse ---"
          ls -la pulse || true
          echo "--- pulse/auto ---"
          ls -la pulse/auto || true
          echo "--- results ---"
          ls -la results || true
          echo "--- results/rgp_ns ---"
          ls -la results/rgp_ns || true

      - name: Verify outputs (schema + presence) with jq
        run: |
          set -euo pipefail
          if [ ! -d results/rgp_ns ]; then
            echo "No results/rgp_ns directory found"; exit 1
          fi
          found=0
          while IFS= read -r -d '' s; do
            found=1
            echo "Checking $s"
            jq -e '
              .dataset and .variant and .nt_test and
              (.nt_test.p != null) and
              (.nt_test.effect_size != null) and
              (.nt_test.significant != null)
            ' "$s" > /dev/null
          done < <(find results/rgp_ns -type f -name summary.json -print0)
          if [ "$found" -eq 0 ]; then
            echo "No summary.json files found under results/rgp_ns/*/*"; exit 1
          fi
          echo "OK: summaries look good."

      - name: Show latest summary in logs
        run: |
          set -e
          latest_dir=$(ls -1dt results/rgp_ns/*/* 2>/dev/null | head -n1 || true)
          if [ -n "$latest_dir" ]; then
            echo "::group::$latest_dir"
            cat "$latest_dir/summary.json" || true
            echo "::endgroup::"
          else
            echo "No run directories found."
          fi

      - name: Commit results & pulses
        run: |
          git config user.name "phi-mesh-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "auto: RGP-NS agent run" || echo "nothing to commit"
          git push

      - name: Refresh Tag Index & Map
        run: |
          python meta/update_tag_index.py
          if [ -f meta/generate_tag_map.py ]; then
            python meta/generate_tag_map.py
          elif [ -f build_tag_browser.py ]; then
            python build_tag_browser.py
          else
            echo "No map builder found; skipping map build."
          fi

      - name: Commit index & map
        run: |
          git add -A
          git commit -m "auto: refresh tag index & map" || echo "nothing to commit"
          git push
