name: Run JHTDB Loader

on:
  workflow_dispatch:
    inputs:
      batch_file:
        description: "Optional YAML of runs (latest first). If set, matrix overrides single inputs."
        required: false
        default: ""
      flow:
        description: "Dataset"
        required: true
        default: "isotropic1024coarse"
      x:      { description: "Probe x", required: true,  default: "0.1" }
      y:      { description: "Probe y", required: true,  default: "0.2" }
      z:      { description: "Probe z", required: true,  default: "0.3" }
      t0:     { description: "Start time", required: true, default: "0.0" }
      dt:     { description: "Δt", required: true, default: "0.002" }
      nsteps: { description: "Samples", required: true, default: "1000" }

permissions:
  contents: write

concurrency:
  group: jhtdb-run
  cancel-in-progress: true

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set_matrix
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{ github.event.inputs.batch_file }}" && -f "${{ github.event.inputs.batch_file }}" ]]; then
            echo "Using batch file: ${{ github.event.inputs.batch_file }}"
            matrix_json="$(python -c 'import json, yaml; d=yaml.safe_load(open("'"${{ github.event.inputs.batch_file }}"'")) or {}; runs=list(reversed(d.get("runs", []))); print(json.dumps({"include": runs}))')"
            printf "matrix=%s\n" "$matrix_json" >> "$GITHUB_OUTPUT"
          else
            echo "Single run parameters"
            printf 'matrix={"include":[{"flow":"%s","x":%s,"y":%s,"z":%s,"t0":%s,"dt":%s,"nsteps":%s}]}\n' \
              "${{ github.event.inputs.flow }}" \
              "${{ github.event.inputs.x }}" \
              "${{ github.event.inputs.y }}" \
              "${{ github.event.inputs.z }}" \
              "${{ github.event.inputs.t0 }}" \
              "${{ github.event.inputs.dt }}" \
              "${{ github.event.inputs.nsteps }}" >> "$GITHUB_OUTPUT"
          fi

  run:
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          # SOAP client + IO + YAML; numpy for analyzer FFT
          pip install suds-community pandas pyarrow pyyaml numpy

      - name: Run JHTDB loader
        env:
          JHTDB_EMAIL: ${{ secrets.JHTDB_EMAIL }}
        shell: bash
        run: |
          set -euo pipefail
          python tools/fd_connectors/jhtdb/jhtdb_loader.py \
            --flow "${{ matrix.flow }}" \
            --x "${{ matrix.x }}" --y "${{ matrix.y }}" --z "${{ matrix.z }}" \
            --t0 "${{ matrix.t0 }}" --dt "${{ matrix.dt }}" --nsteps "${{ matrix.nsteps }}"
          echo "Listing JHTDB directory after load:"
          ls -lh data/jhtdb || true

      - name: Analyze probe(s) and generate pulses
        shell: bash
        run: |
          set -euo pipefail
          ANALYZER="tools/fd_connectors/jhtdb/analyze_probe.py"
          PULSEGEN="tools/fd_connectors/jhtdb/make_pulse_from_probe.py"
          OUTDIR="pulse/auto"
          mkdir -p "$OUTDIR"

          if [[ ! -f "$ANALYZER" ]]; then
            echo "Analyzer not found ($ANALYZER) — skipping analysis."
            exit 0
          fi

          shopt -s nullglob
          echo "Discovering probe CSVs…"
          FILES=( data/jhtdb/*__x*_y*_z*__t0*__dt*__n*.csv.gz )
          printf 'Found %d file(s)\n' "${#FILES[@]}"

          for f in "${FILES[@]}"; do
            echo "Analyzing: $f"
            meta="${f%.csv.gz}.meta.json"
            out="${f%.csv.gz}.analysis.json"
            python "$ANALYZER" --in "$f" --dt "${{ matrix.dt }}" --out "$out"
            if [[ -f "$PULSEGEN" ]]; then
              echo "Making pulse for: $f"
              python "$PULSEGEN" --meta "$meta" --analysis "$out" --outdir "$OUTDIR" --date "$(date -u +%F)"
            else
              echo "Pulse generator not found ($PULSEGEN) — skipping pulse creation."
            fi
          done

          echo "Listing analysis + pulses:"
          ls -lh data/jhtdb/*.analysis.json 2>/dev/null || true
          ls -lh "$OUTDIR" 2>/dev/null || true

      - name: Regenerate tag map data
        shell: bash
        run: |
          set -euo pipefail
          if [[ -f "generate_graph_data.py" ]]; then
            python generate_graph_data.py --pulse-glob "pulse/**/*.yml" --out-js docs/data.js
            echo "docs/data.js regenerated."
          else
            echo "generate_graph_data.py not found — skipping data.js refresh."
          fi

      # Temporarily disabled while verifying pulse creation. Re-enable later.
      - name: Archive orphan JHTDB evidence (auto-clean)
        if: ${{ false }}
        shell: bash
        run: |
          set -euo pipefail
          python tools/fd_connectors/jhtdb/archive_orphan_jhtdb.py

      - name: Upload artifacts (evidence + results)
        uses: actions/upload-artifact@v4
        with:
          name: jhtdb-${{ matrix.flow }}-${{ matrix.x }}-${{ matrix.y }}-${{ matrix.z }}
          path: |
            data/jhtdb/*.csv.gz
            data/jhtdb/*.parquet
            data/jhtdb/*.meta.*
            data/jhtdb/*.analysis.json
            pulse/auto/*.yml
            docs/data.js

      - name: Commit outputs
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Evidence + analyses
          git add -A data/jhtdb
          # Pulses + refreshed map
          git add pulse/auto/*.yml docs/data.js 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No new files to commit."
            exit 0
          fi
          git commit -m "data(jhtdb): probe evidence + analysis + pulses + map refresh (${{ matrix.flow }} @ ${{ matrix.x }},${{ matrix.y }},${{ matrix.z }})"
          git pull --rebase origin main || true
          git push
