name: Run JHTDB Loader

on:
  workflow_dispatch:
    inputs:
      batch_file:
        description: "Optional YAML of runs (latest first). If set, matrix overrides single inputs."
        required: false
        default: ""
      flow:
        description: "Dataset"
        required: true
        default: "isotropic1024coarse"
      x:      { description: "Probe x", required: true,  default: "0.1" }
      y:      { description: "Probe y", required: true,  default: "0.2" }
      z:      { description: "Probe z", required: true,  default: "0.3" }
      t0:     { description: "Start time", required: true, default: "0.0" }
      dt:     { description: "Î”t", required: true, default: "0.002" }
      nsteps: { description: "Samples", required: true, default: "1000" }

permissions:
  contents: write

concurrency:
  group: jhtdb-run
  cancel-in-progress: true

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set_matrix
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{ github.event.inputs.batch_file }}" && -f "${{ github.event.inputs.batch_file }}" ]]; then
            echo "Using batch file: ${{ github.event.inputs.batch_file }}"
            matrix_json="$(python -c 'import json, yaml, sys; d=yaml.safe_load(open("'"${{ github.event.inputs.batch_file }}"'")) or {}; runs=list(reversed(d.get("runs", []))); print(json.dumps({"include": runs}))')"
            printf "matrix=%s\n" "$matrix_json" >> "$GITHUB_OUTPUT"
          else
            echo "Single run parameters"
            printf 'matrix={"include":[{"flow":"%s","x":%s,"y":%s,"z":%s,"t0":%s,"dt":%s,"nsteps":%s}]}\n' \
              "${{ github.event.inputs.flow }}" \
              "${{ github.event.inputs.x }}" \
              "${{ github.event.inputs.y }}" \
              "${{ github.event.inputs.z }}" \
              "${{ github.event.inputs.t0 }}" \
              "${{ github.event.inputs.dt }}" \
              "${{ github.event.inputs.nsteps }}" >> "$GITHUB_OUTPUT"
          fi

  run:
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          # 1) numpy must exist before building pyJHTDB; pin to <2 for compatibility
          pip install "numpy<2"
          # 2) now install the rest
          pip install pyJHTDB==20200909.0 suds-community pandas pyarrow pyyaml

      - name: Run JHTDB loader
        env:
          JHTDB_EMAIL: ${{ secrets.JHTDB_EMAIL }}
        run: |
          set -euo pipefail
          python tools/fd_connectors/jhtdb/jhtdb_loader.py \
            --flow "${{ matrix.flow }}" \
            --x "${{ matrix.x }}" --y "${{ matrix.y }}" --z "${{ matrix.z }}" \
            --t0 "${{ matrix.t0 }}" --dt "${{ matrix.dt }}" --nsteps "${{ matrix.nsteps }}"

      - name: Upload artifacts (evidence)
        uses: actions/upload-artifact@v4
        with:
          name: jhtdb-${{ matrix.flow }}-${{ matrix.x }}-${{ matrix.y }}-${{ matrix.z }}
          path: |
            data/jhtdb/*.csv.gz
            data/jhtdb/*.parquet
            data/jhtdb/*.meta.*

      - name: Commit small outputs
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/jhtdb/*.csv.gz data/jhtdb/*.meta.* 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No new files to commit."
            exit 0
          fi
          git commit -m "data(jhtdb): evidence batch ${{ matrix.flow }} @ (${{ matrix.x }},${{ matrix.y }},${{ matrix.z }}) t0=${{ matrix.t0 }} dt=${{ matrix.dt }} n=${{ matrix.nsteps }}"
          git pull --rebase origin main || true
          git push
