name: Update Tag Index, Map, and Graph Data

on:
  push:
    paths:
      - "phi-mesh/pulse/**/*.yml"
      - "meta/tag_index.yml"
      - "update_tag_index.py"
      - "generate_tag_map.py"
      - "generate_graph_data.py"
      - "docs/graph_layout.js"
      - "docs/sidebar_display.js"
      - ".github/workflows/update_graph_and_tags.yml"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml networkx

      - name: Regenerate tag index
        run: python update_tag_index.py

      - name: Regenerate tag map (HTML)
        run: python generate_tag_map.py

      - name: Regenerate graph data (JS)
        run: python generate_graph_data.py

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add meta/tag_index.yml docs/tag_map.html docs/graph_data.js docs/graph_data.generated.js docs/data.js || true
          git commit -m "Auto: update tag index, tag map, and graph_data.js" || echo "No changes to commit"
          git push || echo "Nothing to push"
