name: Update Tag Index & Graph

on:
  push:
    paths:
      - "phi-mesh/pulse/**/*.yml"
      - "phi-mesh/pulse/**/*.yaml"
      - "meta/tag_index_utils.py"
      - "update_tag_index.py"
      - "generate_graph_data.py"
      - "docs/*.js"
      - "docs/tag_map.html"

jobs:
  build-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Regenerate tag index
        run: python update_tag_index.py

      - name: Generate graph data
        run: python generate_graph_data.py

      - name: Inject build hash in tag_map.html (cache-busting without new files)
        run: |
          HASH=$(git rev-parse --short HEAD)
          sed -i "s/__BUILD_HASH__/${HASH}/g" docs/tag_map.html

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add meta/tag_index.yml docs/data.js docs/graph_data.js docs/link_index.js docs/tag_map.html
          git diff --cached --quiet || git commit -m "auto: update tag index & graph (build $GITHUB_SHA)"
          git push || true
